
export const FETCH_USER_REQUEST = 'FETCH_USER_SUCCESS';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const EDIT_USER_REQUEST = 'EDIT_USER_SUCCESS';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';
export const EDIT_USER_IDLE = 'EDIT_USER_IDLE';

export const APPLY_JOB_REQUEST = 'APPLY_JOB_REQUEST';
export const APPLY_JOB_SUCCESS = 'APPLY_JOB_SUCCESS';
export const APPLY_JOB_ERROR = 'APPLY_JOB_ERROR';

export const SAVE_JOB_REQUEST = 'SAVE_JOB_REQUEST';
export const SAVE_JOB_SUCCESS = 'SAVE_JOB_SUCCESS';
export const SAVE_JOB_ERROR = 'SAVE_JOB_ERROR';

export const UNSAVE_JOB_REQUEST = 'UNSAVE_JOB_REQUEST';
export const UNSAVE_JOB_SUCCESS = 'UNSAVE_JOB_SUCCESS';
export const UNSAVE_JOB_ERROR = 'UNSAVE_JOB_ERROR';